In [1]:
import pandas as pd

In [2]:
faculty = pd.read_csv("../raw_data/faculty.csv")

subjects = pd.read_csv("../raw_data/subjects.csv")

workload = pd.read_csv("../raw_data/workload.csv")
faculty

   faculty_id faculty_name department
0           1  Amit Sharma        CSE
1           2     Riya Das        ECE
2           3    John Paul         IT
3           4    Sara Khan         ME
4           5          NaN        CSE

In [3]:
subjects

   subject_id    subject_name
0         101    Data Science
1         102        Circuits
2         103            DBMS
3         104  Thermodynamics
4         105              AI

In [4]:
workload

   workload_id  faculty_id  subject_id  hours_assigned semester
0            1           1         101             4.0     Sem1
1            2           2         102             3.0     Sem1
2            3           3         103             5.0     Sem2
3            4           4         104            -2.0     Sem2
4            5           5         105             NaN     Sem1
5            5           5         105             NaN     Sem1

In [7]:
# Remove duplicates
workload = workload.drop_duplicates().copy()

# Fix missing faculty names
faculty["faculty_name"] = faculty["faculty_name"].fillna("Unknown")

# Fix negative hours
workload["hours_assigned"] = workload["hours_assigned"].abs()

# Remove rows with missing hours
workload = workload.dropna()

print("\nCleaned Faculty:")
faculty

Cleaned Faculty:

   faculty_id faculty_name department
0           1  Amit Sharma        CSE
1           2     Riya Das        ECE
2           3    John Paul         IT
3           4    Sara Khan         ME
4           5      Unknown        CSE

In [8]:
workload

   workload_id  faculty_id  subject_id  hours_assigned semester
0            1           1         101             4.0     Sem1
1            2           2         102             3.0     Sem1
2            3           3         103             5.0     Sem2
3            4           4         104             2.0     Sem2

In [9]:
merged_df = workload.merge(
    faculty,
    on="faculty_id"
)

merged_df = merged_df.merge(
    subjects,
    on="subject_id"
)

print("\nMerged Dataset:")
merged_df

Merged Dataset:

,workload_id,faculty_id,subject_id,hours_assigned,semester,faculty_name,department,subject_name
0,1,1,101,4.0,Sem1,Amit Sharma,CSE,Data Science
1,2,2,102,3.0,Sem1,Riya Das,ECE,Circuits
2,3,3,103,5.0,Sem2,John Paul,IT,DBMS
3,4,4,104,2.0,Sem2,Sara Khan,ME,Thermodynamics

In [10]:
merged_df.to_csv(
    "../processed_data/merged_workload.csv",
    index=False
)

print("Merged data saved successfully")

Merged data saved successfully